int maxState = 2; 
int t = 7;
int move_left(int state, int move){
	int nextState;
	if (state == 0) {
		if (move == 0) {
			nextState = ??; 
		} else if (move == 1) {
			nextState = ??; 
		} else if (move == 2) {
			nextState = ??; 
		} else if (move == 3) {
			nextState = ??; 
		} else { 
			assert 0;
		}
	} else if (state == 1) {
		if (move == 0) {
			nextState = ??; 
		} else if (move == 1) {
			nextState = ??; 
		} else if (move == 2) {
			nextState = ??; 
		} else if (move == 3) {
			nextState = ??; 
		} else { 
			assert 0;
		}
	} else {
		assert 0;
	}
	assert (nextState < maxState);
 	return nextState;
} 

int move_right(int state, int move){
	int nextState;
	if (state == 0) {
		if (move == 0) {
			nextState = ??; 
		} else if (move == 1) {
			nextState = ??; 
		} else if (move == 2) {
			nextState = ??; 
		} else if (move == 3) {
			nextState = ??; 
		} else { 
			assert 0;
		}
	} else if (state == 1) {
		if (move == 0) {
			nextState = ??; 
		} else if (move == 1) {
			nextState = ??; 
		} else if (move == 2) {
			nextState = ??; 
		} else if (move == 3) {
			nextState = ??; 
		} else { 
			assert 0;
		}
	} else {
		assert 0;
	}
	assert (nextState < maxState);
 	return nextState;
} 

int move_up(int state, int move){
	int nextState;
	if (state == 0) {
		if (move == 0) {
			nextState = ??; 
		} else if (move == 1) {
			nextState = ??; 
		} else if (move == 2) {
			nextState = ??; 
		} else if (move == 3) {
			nextState = ??; 
		} else { 
			assert 0;
		}
	} else if (state == 1) {
		if (move == 0) {
			nextState = ??; 
		} else if (move == 1) {
			nextState = ??; 
		} else if (move == 2) {
			nextState = ??; 
		} else if (move == 3) {
			nextState = ??; 
		} else { 
			assert 0;
		}
	} else {
		assert 0;
	}
	assert (nextState < maxState);
 	return nextState;
} 

int move_down(int state, int move){
	int nextState;
	if (state == 0) {
		if (move == 0) {
			nextState = ??; 
		} else if (move == 1) {
			nextState = ??; 
		} else if (move == 2) {
			nextState = ??; 
		} else if (move == 3) {
			nextState = ??; 
		} else { 
			assert 0;
		}
	} else if (state == 1) {
		if (move == 0) {
			nextState = ??; 
		} else if (move == 1) {
			nextState = ??; 
		} else if (move == 2) {
			nextState = ??; 
		} else if (move == 3) {
			nextState = ??; 
		} else { 
			assert 0;
		}
	} else {
		assert 0;
	}
	assert (nextState < maxState);
 	return nextState;
} 


harness void main() {
	int init_action = 1;
	int[t] true_actions = {3,1,3,1,3,1,3};
	int init_state_l = ??;
	int max_acc_l = ??;
	int init_state_r = 0;
	int max_acc_r = ??;
	int init_state_u = ??;
	int max_acc_u = ??;
	int init_state_d = ??;
	int max_acc_d = ??;
	int l = move_left(init_state_l, init_action);
	int r = move_right(init_state_r, init_action);
	int u = move_up(init_state_u, init_action);
	int d = move_down(init_state_d, init_action);
	assert ((l <= max_acc_l) && (r > max_acc_r) && (u > max_acc_u) && (d > max_acc_d)) || ((r <= max_acc_r) && (l > max_acc_l) && (u > max_acc_u) && (d > max_acc_d)) || ((u <= max_acc_u) && (l > max_acc_l) && (r > max_acc_r) && (d > max_acc_d)) || ((d <= max_acc_d) && (l > max_acc_l) && (r > max_acc_r) && (u > max_acc_u));
	int next;
	if (l <= max_acc_l) {
		next = 0;
	} else if (r <= max_acc_r) {
		next = 1;
	} else if (u <= max_acc_u) {
		next = 2;
	} else if (d <= max_acc_d) {
		next = 3;
	}
	assert (next == true_actions[0]);
	
	for (int i=1; i<t; i++) {
		l = move_left(l, next);
		r = move_right(r, next);
		u = move_up(u, next);
		d = move_down(d, next);
		assert ((l <= max_acc_l) && (r > max_acc_r) && (u > max_acc_u) && (d > max_acc_d)) || ((r <= max_acc_r) && (l > max_acc_l) && (u > max_acc_u) && (d > max_acc_d)) || ((u <= max_acc_u) && (l > max_acc_l) && (r > max_acc_r) && (d > max_acc_d)) || ((d <= max_acc_d) && (l > max_acc_l) && (r > max_acc_r) && (u > max_acc_u));
		if (l <= max_acc_l) {
			next = 0;
		} else if (r <= max_acc_r) {
			next = 1;
		} else if (u <= max_acc_u) {
			next = 2;
		} else if (d <= max_acc_d) {
			next = 3;
		}
		assert (next == true_actions[i]);
	}
}
